### ISSUE TITLE
how to change the source 

### ISSUE THREAD

**Issue by Rnoyonr** [jhu-ep-coursera/fullstack-course1-module2#34]
**_# Analyze the outcome of the original script and state the reasons why each of the first three (3) tests fail and how they could be made to succeed.

$ ruby module2_lesson1_formative.rb

I guess nothing matched... But why?

Change the source code of the solution to verify your conclusions._**

how do i change source code..
i have cloned the https://github.com/jhu-ep-coursera/fullstack-course1-module2.git repo
now where do i change the code.

**Comment by kalmanh** [comment]
Change the code inside module2_lesson1_formative.rb file located locally in your repo (Assignments/Lesson01-Assignment01-Case-Statement/student-start/module2_lesson1_formative.rb)
