### ISSUE TITLE
Not able to download fullstack-course1-module2 folder

### ISSUE THREAD

**Issue by puneetgaurr** [jhu-ep-coursera/fullstack-course1-module2#38]
I am not able to download this folder to complete my assessment. Please have a look into this and let me know if I'm following anything wrong here.

git clone https://github.com/jhu-ep-coursera/fullstack-course1-module2/tree/master/Assignments/Lesson02-Assignment01-Collections/student-start
Cloning into 'student-start'...
remote: Not Found

**Comment by ravindra9278** [comment]
You are using wrong remote url use below url
git clone https://github.com/jhu-ep-coursera/fullstack-course1-module2.git

**Comment by LeonardMuia** [comment]
I have had the same problem. Can someone help me please?
![sketch](https://user-images.githubusercontent.com/18761569/37258322-03d00d4c-2587-11e8-8422-9feb5277449d.png)

**Comment by prusswan** [comment]
@LeonardMuia Your problem is caused by a different error, see this: https://stackoverflow.com/questions/48947351/why-is-my-rails-app-not-pushing-to-github-error1407742essl

**Comment by carmenvande** [comment]
I had the same error as @LeonardMuia, the link from @prusswan led me to this:

git clone git://github.com/jhu-ep-coursera/fullstack-course1-module2.git

and it worked. Thanks

**Comment by LeonardMuia** [comment]
Thank you guys, it has worked.
