### ISSUE TITLE
Possible bug in test

### ISSUE THREAD

**Issue by Kanzll** [jhu-ep-coursera/fullstack-course1-module2#41]
Hi,
I had passed one hours with the assignment #3 and I get the right result but the tests still show me errors, after that I found the following [Link](https://stackoverflow.com/questions/48242127/ruby-on-rails-coursera-class-bug-in-tests#) and I have resolved the problem, can you check that.

Thank you !

**Comment by kalmanh** [comment]
You are correct - I have addressed the issue with the following commit https://github.com/jhu-ep-coursera/fullstack-course1-module2/commit/bca60ae40a092c89504d5ad3cc6721f5e9e9f6a3
